path: /content/gdrive/My Drive/Colab Notebooks/major_project # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

# Classes
names:
  0: ambulance